### ISSUE TITLE
Error PHP...

### ISSUE THREAD

**Issue by ducarpit** [dg9vh/MMDVMHost-Dashboard#167]
Hi,
this morning i tried to connect my mmdvm dashboard but i get this error in the /var/log/lighttpd/error.log file and i couldn't access it:

```
2017-12-04 09:57:50: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (ary file /opt/MMDVMHost) at position 0 (a): The timezone could not be found in the database' in /var/www/html/include/tools.php:111
2017-12-04 09:57:50: (mod_fastcgi.c.2543) FastCGI-stderr: Stack trace:
2017-12-04 09:57:50: (mod_fastcgi.c.2543) FastCGI-stderr: #0 /var/www/html/include/tools.php(111): DateTime->__construct('ary file /opt/M...')
2017-12-04 09:57:50: (mod_fastcgi.c.2543) FastCGI-stderr: #1 /var/www/html/include/functions.php(464): convertTimezone('ary file /opt/M...')
2017-12-04 09:57:50: (mod_fastcgi.c.2543) FastCGI-stderr: #2 /var/www/html/include/functions.php(488): getHeardList(Array, false)
2017-12-04 09:57:50: (mod_fastcgi.c.2543) FastCGI-stderr: #3 /var/www/html/include/init.php(18): getLastHeard(Array, false)
2017-12-04 09:57:50: (mod_fastcgi.c.2543) FastCGI-stderr: #4 /var/www/html/index.php(29): include('/var/www/html/i...')
2017-12-04 09:57:50: (mod_fastcgi.c.2543) FastCGI-stderr: #5 {main}
2017-12-04 09:57:50: (mod_fastcgi.c.2543) FastCGI-stderr:   thrown in /var/www/html/include/tools.php on line 111
```

Can someone help me?
Thanks

**Comment by dg9vh** [comment]
Please check if the Webserver User could run the MMDVMHost with sudo -u www-user or similar.KimDG9VH-- Amateurfunk ist das, was uns verbindet! Bleiben wir in Kontakt! Ortsverband Q05, VölklingenAm 04.12.2017 10:03 schrieb ducarpit <notifications@github.com>:Hi,
this morning i tried to connect my mmdvm dashboard but i get this error in the /var/log/lighttpd/error.log file and i couldn't access it:
2017-12-04 09:57:50: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (ary file /opt/MMDVMHost) at position 0 (a): The timezone could not be found in the database' in /var/www/html/include/tools.php:111
2017-12-04 09:57:50: (mod_fastcgi.c.2543) FastCGI-stderr: Stack trace:
2017-12-04 09:57:50: (mod_fastcgi.c.2543) FastCGI-stderr: #0 /var/www/html/include/tools.php(111): DateTime->__construct('ary file /opt/M...')
2017-12-04 09:57:50: (mod_fastcgi.c.2543) FastCGI-stderr: #1 /var/www/html/include/functions.php(464): convertTimezone('ary file /opt/M...')
2017-12-04 09:57:50: (mod_fastcgi.c.2543) FastCGI-stderr: #2 /var/www/html/include/functions.php(488): getHeardList(Array, false)
2017-12-04 09:57:50: (mod_fastcgi.c.2543) FastCGI-stderr: #3 /var/www/html/include/init.php(18): getLastHeard(Array, false)
2017-12-04 09:57:50: (mod_fastcgi.c.2543) FastCGI-stderr: #4 /var/www/html/index.php(29): include('/var/www/html/i...')
2017-12-04 09:57:50: (mod_fastcgi.c.2543) FastCGI-stderr: #5 {main}
2017-12-04 09:57:50: (mod_fastcgi.c.2543) FastCGI-stderr:   thrown in /var/www/html/include/tools.php on line 111

Can someone help me?
Thanks

**Comment by ducarpit** [comment]
Hi, this is my result:

```
pi@raspberryMMDVM:~ $ sudo -u www-user
sudo: unknown user: www-user
sudo: unable to initialize policy plugin
```
But in the instruction there is a line to insert a new group, not a new user called www-user

**Comment by ducarpit** [comment]
I solved deleting my MMDVM log in the MMDVM directory.....
That's strange because i have this log configuration in my MMDVM.ini file:

```
[Log]
Logging levels=4
DisplayLevel=1
FileLevel=2
FilePath=.
FileRoot=MMDVM
```

**Comment by dg9vh** [comment]
Try to find out which user is running the Webserver. Maybe www-data?-- Amateurfunk ist das, was uns verbindet! Bleiben wir in Kontakt! Ortsverband Q05, VölklingenAm 04.12.2017 10:52 schrieb ducarpit <notifications@github.com>:Hi, this is my result:
pi@raspberryMMDVM:~ $ sudo -u www-user
sudo: unknown user: www-user
sudo: unable to initialize policy plugin
