### ISSUE TITLE
The dashboard works halfway

### ISSUE THREAD

**Issue by ik4nzd** [dg9vh/MMDVMHost-Dashboard#209]
Sorry if I make another report.
We have installed the dashboard on our repeater for several years.
For some days, probably after installing the latest updates (including FM), the dashboard opens halfway.
The real-time passages appear correctly in the boxes above, but the lower part does not open.
I tried with various browsers, with various computers with other radio amateur friends, and with various levels of the log, unfortunately without result.
Will you be able to have the complete dashboard?
Thanks

![Immagine](https://user-images.githubusercontent.com/29512684/83451706-b42a4300-a457-11ea-9989-57b556734125.jpg)

**Comment by ik4nzd** [comment]
I'm doing some tests to understand when this problem starts.
If I delete the log file from MMDVM, the dashboard works regularly, showing the empty fields, as shown in the image.
When the log is created, I continue to see everything normally BUT UNTIL THE BROWSER IS CLOSED AND REOPENED, OR UNTIL THE PAGE IS UPDATED WITH F5.
From that moment the page view returns to show only the upper part, and at most the passages in real time.
It's very strange.....
![Immagine](https://user-images.githubusercontent.com/29512684/83492835-29c3fc80-a4b4-11ea-85f1-db02d556a332.jpg)

**Comment by dg9vh** [comment]
Please take a look at the error.log of your webserver... I think there is happening something strange.

**Comment by dg9vh** [comment]
Maybe there could be a correlation with https://github.com/dg9vh/MMDVMHost-Dashboard/issues/207

**Comment by ik4nzd** [comment]
> Please take a look at the error.log of your webserver... I think there is happening something strange.
---
2020-06-02 09:25:16: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Fatal error:  Uncaught exception 'Exception' with message 'DateInterval::__construct(): Unknown or bad format (PTS)' in /var/www/html/include/functions.php:608
2020-06-02 09:25:16: (mod_fastcgi.c.2702) FastCGI-stderr: Stack trace:
2020-06-02 09:25:16: (mod_fastcgi.c.2702) FastCGI-stderr: #0 /var/www/html/include/functions.php(608): DateInterval->__construct('PTS')
2020-06-02 09:25:16: (mod_fastcgi.c.2702) FastCGI-stderr: #1 /var/www/html/ajax.php(34): getActualMode(Array, Array)
2020-06-02 09:25:16: (mod_fastcgi.c.2702) FastCGI-stderr: #2 {main}
2020-06-02 09:25:16: (mod_fastcgi.c.2702) FastCGI-stderr:   thrown in /var/www/html/include/functions.php on line 608
2020-06-02 09:25:17: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Fatal error:  Uncaught exception 'Exception' with message 'DateInterval::__construct(): Unknown or bad format (PTS)' in /var/www/html/include/functions.php:608
2020-06-02 09:25:17: (mod_fastcgi.c.2702) FastCGI-stderr: Stack trace:
2020-06-02 09:25:17: (mod_fastcgi.c.2702) FastCGI-stderr: #0 /var/www/html/include/functions.php(608): DateInterval->__construct('PTS')
2020-06-02 09:25:17: (mod_fastcgi.c.2702) FastCGI-stderr: #1 /var/www/html/ajax.php(34): getActualMode(Array, Array)
2020-06-02 09:25:17: (mod_fastcgi.c.2702) FastCGI-stderr: #2 {main}
2020-06-02 09:25:17: (mod_fastcgi.c.2702) FastCGI-stderr:   thrown in /var/www/html/include/functions.php on line 608
2020-06-02 09:25:18: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Fatal error:  Uncaught exception 'Exception' with message 'DateInterval::__construct(): Unknown or bad format (PTS)' in /var/www/html/include/functions.php:608
2020-06-02 09:25:18: (mod_fastcgi.c.2702) FastCGI-stderr: Stack trace:
2020-06-02 09:25:18: (mod_fastcgi.c.2702) FastCGI-stderr: #0 /var/www/html/include/functions.php(608): DateInterval->__construct('PTS')
2020-06-02 09:25:18: (mod_fastcgi.c.2702) FastCGI-stderr: #1 /var/www/html/ajax.php(34): getActualMode(Array, Array)
2020-06-02 09:25:18: (mod_fastcgi.c.2702) FastCGI-stderr: #2 {main}
2020-06-02 09:25:18: (mod_fastcgi.c.2702) FastCGI-stderr:   thrown in /var/www/html/include/functions.php on line 608
2020-06-02 09:25:19: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Fatal error:  Uncaught exception 'Exception' with message 'DateInterval::__construct(): Unknown or bad format (PTS)' in /var/www/html/include/functions.php:608
2020-06-02 09:25:19: (mod_fastcgi.c.2702) FastCGI-stderr: Stack trace:
2020-06-02 09:25:19: (mod_fastcgi.c.2702) FastCGI-stderr: #0 /var/www/html/include/functions.php(608): DateInterval->__construct('PTS')
2020-06-02 09:25:19: (mod_fastcgi.c.2702) FastCGI-stderr: #1 /var/www/html/ajax.php(34): getActualMode(Array, Array)
2020-06-02 09:25:19: (mod_fastcgi.c.2702) FastCGI-stderr: #2 {main}
2020-06-02 09:25:19: (mod_fastcgi.c.2702) FastCGI-stderr:   thrown in /var/www/html/include/functions.php on line 608

---
The log is full of these error lines
---




> Maybe there could be a correlation with #207

I don't know, but I think not .....

'73 de Adam, IK4NZD

**Comment by dg9vh** [comment]
could you please use cat to get all of the lines and not open the file with nano?

I can't see the line-numbers the errors happening in...

**Comment by ik4nzd** [comment]
> could you please use cat to get all of the lines and not open the file with nano?
> I can't see the line-numbers the errors happening in...

sorry....they are now complete

**Comment by dg9vh** [comment]
What version of the Dashboard you are using? is it actual version?

**Comment by ik4nzd** [comment]
I do not know. 
The dashboard has been installed since 2018 and has always worked until May 24, 2020. 
Now I try to understand which version I have, but it will probably be old ...

**Comment by ik4nzd** [comment]
MMDVMHost-Dashboard V 20180404-3 (GitID unknown) | Last Reload 2020-06-02, 22:59:27 (Europe/Rome) | stop refreshing | get your own at: https://github.com/dg9vh/MMDVMHost-Dashboard | Follow me @DG9VH | Credits

**Comment by dg9vh** [comment]
This Version is far away from being actual... please get a new copy of the files... if using git, you just can do a git pull for example...

**Comment by ik4nzd** [comment]
I have updated with git clone, and now I am in this situation
--
MMDVMHost-Dashboard V 20200602-1 (GitID unknown)
--
I have also updated the system with update/upgrade, but the problem remains the same as before.
This is a new log
---
2020-06-02 23:52:07: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Fatal error:  Uncaught exception 'Exception' with message 'DateInterval::__construct(): Unknown or bad format (PTS)' in /var/www/html/include/functions.php:645
2020-06-02 23:52:07: (mod_fastcgi.c.2702) FastCGI-stderr: Stack trace:
2020-06-02 23:52:07: (mod_fastcgi.c.2702) FastCGI-stderr: #0 /var/www/html/include/functions.php(645): DateInterval->__construct('PTS')
2020-06-02 23:52:07: (mod_fastcgi.c.2702) FastCGI-stderr: #1 /var/www/html/ajax.php(34): getActualMode(Array, Array)
2020-06-02 23:52:07: (mod_fastcgi.c.2702) FastCGI-stderr: #2 {main}
2020-06-02 23:52:07: (mod_fastcgi.c.2702) FastCGI-stderr:   thrown in /var/www/html/include/functions.php on line 645
2020-06-02 23:52:07: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Fatal error:  Uncaught exception 'Exception' with message 'DateInterval::__construct(): Unknown or bad format (PTS)' in /var/www/html/include/functions.php:645
2020-06-02 23:52:07: (mod_fastcgi.c.2702) FastCGI-stderr: Stack trace:
2020-06-02 23:52:07: (mod_fastcgi.c.2702) FastCGI-stderr: #0 /var/www/html/include/functions.php(645): DateInterval->__construct('PTS')
2020-06-02 23:52:07: (mod_fastcgi.c.2702) FastCGI-stderr: #1 /var/www/html/ajax.php(34): getActualMode(Array, Array)
2020-06-02 23:52:07: (mod_fastcgi.c.2702) FastCGI-stderr: #2 {main}
2020-06-02 23:52:07: (mod_fastcgi.c.2702) FastCGI-stderr:   thrown in /var/www/html/include/functions.php on line 645

**Comment by dg9vh** [comment]
I have a look at it this evening... Now vy busy during the day.

**Comment by ik4nzd** [comment]
Hi Kim.
Don't worry about the times.
If you need more tests, I am at your disposal.
Ciao

**Comment by dg9vh** [comment]
could you please post your MMDVM.ini? I want to check some configurations on your side...

**Comment by ik4nzd** [comment]
[MMDVM.ini.txt](https://github.com/dg9vh/MMDVMHost-Dashboard/files/4725022/MMDVM.ini.txt)

**Comment by dg9vh** [comment]
Hi,

I think, you are producing the Error by having this configuration in your General-Section:
`# ModeHang=10`
`# RFModeHang=10`
`NetModeHang=10`

You should either use ModeHang = 10 or both RFModeHang and NetModeHang... but what you are doing there is only defining NetModeHang so my Dashboard crashes on RF-transmissions because of following:

It checks if ModeHang is set (in your case: no, because you commented it out). It found, that you commented it out, so it assumes to use the RFModeHang and then it goes on fire...

Please remove the # in front of RFModeHang and try again!

**Comment by ik4nzd** [comment]
Hi Kim.
You're right, without # everything started working again.
I made millions of changes to that file and made the mistake.
I apologize for making you waste time.
Now the dashboard works, but I still don't see the TA, as in a issue # 205.
Thanks again.
'73 de Adam, IK4NZD

**Comment by dg9vh** [comment]
Ok... now with your config-file, I take a look at the corresponding part of it to see, if I can find something there :-) I close this issue...

73 so long :-)
